# Analysis the Data

## Merging & Joining Data

In [2]:
import pandas as pd

In [8]:
df1 = pd.read_csv('1_health_supplement.csv')  #data page 1

In [11]:
df1

,Product Name,Discount Prices(?),Actual Prices(?),Weight/Type,Discount Percentage(%),Rating,Users
0,Wellcore Micronised Creatine Monohydrate | Lab...,599,749,"122 g, Tropical Tango",20% off,4.3,"2,51,934"
1,BIGMUSCLES NUTRITION Premium Gold Whey Protein,"1,499","2,899","1 kg, Belgian Chocolate",48% off,4.1,"99,351"
2,NutraEats Protein Plus Supplement Whey Protein...,459,599,"200 g, Chocolate",23% off,4.3,"2,51,934"
3,NutraEats Protein Plus Supplement Whey Protein...,489,899,"300 g, Chocolate",45% off,4.3,"2,51,934"
4,NutraEats Protein Plus Supplement Whey Protein...,528,799,"250 g, Chocolate",33% off,4.2,"1,467"
...,...,...,...,...,...,...,...
270,Dr. Morepen LightLife On-The-Go Meal |19g Prot...,623,"1,458","300 g, Chocolate",79% off,4.0,"20,927"
271,"POWERLIFT for Muscle Mass Gain with Shaker, Hi...",759,"3,999","1 kg, Rich Chocolate",33% off,4.0,442
272,"PATANJALI Nutrela Slim choice, 500 Gm Whey Pro...","1,083","1,599","500 g, vanilla",50% off,3.8,"1,745"
273,Labrada nutrition Super Mass Gainer 3kg |(Dulc...,"2,564",849,"3 kg, Dulche De Leche",20% off,4.1,600
274,Primemuscle Nutritions Creatine monohydrate wi...,225,799,"100 g, 100g+ Shaker",48% off,4.0,332

In [4]:
df2 = pd.read_csv('2_health_supplement.csv') #data page 2

In [14]:
df2

,Product Name,Discount Prices(?),Actual Prices(?),Weight/Type,Discount Percentage(%),Rating,Users
0,Kapiva Himalayan Shilajit Resin|Rich in Fulvic...,463,799,10 g,42% off,4.1,"1,32,501"
1,Kapiva Shilajit Gold | Contains 24 Carat Gold ...,899,"1,199",60 Capsules,25% off,3.9,"13,397"
2,"Baidyanath Giloy Juice 1 Litre, Natural Immuni...",195,410,1,35% off,4.2,"4,238"
3,Multani Chyawanprash Special Enriched With Kes...,266,255,1 kg,7% off,4.3,789
4,"Dr Vitasta ayurvedic medicine for weight gain,...",330,630,"Pack of 2, 60 Capsules",79% off,4.1,51
...,...,...,...,...,...,...,...
805,Hakeem Baqai's Night Safari 40 Pills (Each 80 ...,263,"1,360","Pack of 2, 80 Tablets",41% off,4.7,12
806,Kapiva Himalayan Shilajit Resin|Rich in Fulvic...,359,630,10 g,5% off,4.2,"6,435"
807,Kapiva Shilajit Gold | Contains 24 Carat Gold ...,"1,048",165,60 Capsules,20% off,4.0,58
808,fazeelat creations KASHMIRI AYURVEDIC SHILAJIT...,"1,525",429,40 g,17% off,4.2,307
809,ALPHA AYURVEDA Sakhi Tone - Ayurvedic Weight G...,198,649,500 g,26% off,3.8,"1,012"

In [5]:
df3 = pd.read_csv('3_health_supplement.csv') #data page 3

In [13]:
df3

,Product Name,Discount Prices(?),Actual Prices(?),Weight/Type,Discount Percentage(%),Rating,Users
0,deconstruct Sunscreen - SPF 55+ PA+++ Lightwei...,314,349,50 g,10% off,4.2,"1,41,746"
1,Cetaphil Oily Skin Cleanser Face Wash,608,699,125 ml,13% off,4.3,"43,936"
2,BIOTIQUE Rice Water & Niacinamide Gel |Removes...,165,259,100 ml,36% off,4.2,"3,104"
3,TRU HAIR & SKIN Radiant Glow Skincare Trio: Vi...,415,967,3 Items in the set,57% off,4.1,87
4,"Skinkraft Vitamin C Radiance Kit, Face Wash + ...","1,399","1,946",4 Items in the set,28% off,4.0,807
...,...,...,...,...,...,...,...
782,GLAMVEDA Glass Skin Rice Ceramide Facewash+Soa...,225,429,200 ml,22% off,4.4,76
783,Cosrx BHA Blackhead Power Liquid Exfoliant | B...,226,949,100 g,35% off,4.3,"12,701"
784,"Organic Netra Rose Water Toner With Vitamin C,...",464,720,9 g,5% off,4.8,65
785,"JEEVIKA HERBS MANGO SEEDS POWDER , MANGO GUTHL...",799,"1,596",50 g,28% off,4.3,644
786,HipHop Skincare Charcoal Nose Strips (Men) - B...,496,499,30 ml,56% off,4.4,583

In [6]:
df4 = pd.read_csv('4_health_supplement.csv')  #data page 4

In [12]:
df4

,Product Name,Discount Prices(?),Actual Prices(?),Weight/Type,Discount Percentage(%),Rating,Users
0,Cetaphil DAM DAILY ADVANCE ULTRA HYDRATING LOTION,237,279,30 g,15% off,4.2,"64,529"
1,Parachute Advansed Deep Nourish Body Lotion,323,850,800 ml,62% off,4.4,"1,98,315"
2,BELLAVITA DATE WOMAN Perfume Body Lotion|Helps...,225,325,200 ml,30% off,4.5,"5,567"
3,Joy Relaxing Green Tea Body Serum Lotion | Ref...,174,325,300 ml,46% off,4.1,"6,406"
4,Santoor Body Lotion for Extra Moisturising Wit...,180,400,400 ml,55% off,4.4,202
...,...,...,...,...,...,...,...
907,Vaseline Healthy Bright Sun+Pollution Protecti...,593,499,400 ml,85% off,4.4,"20,469"
908,efatop NEXT Lotion 150ml For Intense Moisturizer,569,300,150 ml,55% off,3.9,17
909,Rubz Cherry Blossom Body Milk with Cherry Blos...,353,525,1 L,22% off,4.1,"1,167"
910,Parachute Advansed Advansed Soft Touch Body Lo...,349,80,800 ml,24% off,4.6,269
911,POND's Niacinamide Nourishing Body Lotion 400 ml,241,585,400 ml,8% off,4.6,860

In [9]:
df5 = pd.concat([df1,df2,df3,df4])   #concat all data page (1,2,3,4) in 5 all data in here

In [10]:
df5   #it is the final data upgrade ,onward what we perform operation by using this data

,Product Name,Discount Prices(?),Actual Prices(?),Weight/Type,Discount Percentage(%),Rating,Users
0,Wellcore Micronised Creatine Monohydrate | Lab...,599,749,"122 g, Tropical Tango",20% off,4.3,"2,51,934"
1,BIGMUSCLES NUTRITION Premium Gold Whey Protein,"1,499","2,899","1 kg, Belgian Chocolate",48% off,4.1,"99,351"
2,NutraEats Protein Plus Supplement Whey Protein...,459,599,"200 g, Chocolate",23% off,4.3,"2,51,934"
3,NutraEats Protein Plus Supplement Whey Protein...,489,899,"300 g, Chocolate",45% off,4.3,"2,51,934"
4,NutraEats Protein Plus Supplement Whey Protein...,528,799,"250 g, Chocolate",33% off,4.2,"1,467"
...,...,...,...,...,...,...,...
907,Vaseline Healthy Bright Sun+Pollution Protecti...,593,499,400 ml,85% off,4.4,"20,469"
908,efatop NEXT Lotion 150ml For Intense Moisturizer,569,300,150 ml,55% off,3.9,17
909,Rubz Cherry Blossom Body Milk with Cherry Blos...,353,525,1 L,22% off,4.1,"1,167"
910,Parachute Advansed Advansed Soft Touch Body Lo...,349,80,800 ml,24% off,4.6,269
911,POND's Niacinamide Nourishing Body Lotion 400 ml,241,585,400 ml,8% off,4.6,860

In [26]:
df5.to_csv('5_total_health_supplement.csv',index=False)   #push our final data(df5) to a csv file

## Exploring the Data with Analysis

In [30]:
df = pd.read_csv('total_health_supplement.csv')

In [31]:
df.head()   #it give first 5 rows

,Product Name,Discount Prices(?),Actual Prices(?),Weight/Type,Discount Percentage(%),Rating,Users
0,Wellcore Micronised Creatine Monohydrate | Lab...,599,749,"122 g, Tropical Tango",20% off,4.3,"2,51,934"
1,BIGMUSCLES NUTRITION Premium Gold Whey Protein,"1,499","2,899","1 kg, Belgian Chocolate",48% off,4.1,"99,351"
2,NutraEats Protein Plus Supplement Whey Protein...,459,599,"200 g, Chocolate",23% off,4.3,"2,51,934"
3,NutraEats Protein Plus Supplement Whey Protein...,489,899,"300 g, Chocolate",45% off,4.3,"2,51,934"
4,NutraEats Protein Plus Supplement Whey Protein...,528,799,"250 g, Chocolate",33% off,4.2,"1,467"

In [32]:
df.tail()  #iit gives last 5 rows

,Product Name,Discount Prices(?),Actual Prices(?),Weight/Type,Discount Percentage(%),Rating,Users
2779,Vaseline Healthy Bright Sun+Pollution Protecti...,593,499,400 ml,85% off,4.4,"20,469"
2780,efatop NEXT Lotion 150ml For Intense Moisturizer,569,300,150 ml,55% off,3.9,17
2781,Rubz Cherry Blossom Body Milk with Cherry Blos...,353,525,1 L,22% off,4.1,"1,167"
2782,Parachute Advansed Advansed Soft Touch Body Lo...,349,80,800 ml,24% off,4.6,269
2783,POND's Niacinamide Nourishing Body Lotion 400 ml,241,585,400 ml,8% off,4.6,860

In [33]:
df.describe()   #describe the data

            Rating
count  2784.000000
mean      4.236458
std       0.262913
min       1.000000
25%       4.100000
50%       4.300000
75%       4.400000
max       5.000000

In [34]:
df.info()   #all about information data frame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2784 entries, 0 to 2783
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Product Name            2784 non-null   object
 1   Discount Prices(?)      2784 non-null   object
 2   Actual Prices(?)        2784 non-null   object
 3   Weight/Type             2784 non-null   object
 4   Discount Percentage(%)  2784 non-null   object
 5   Rating                  2784 non-null   float64
 6   Users                   2784 non-null   object
dtypes: float64(1), object(6)
memory usage: 152.4+ KB

In [35]:
df.columns   #all columns name

Index(['Product Name', 'Discount Prices(?)', 'Actual Prices(?)', 'Weight/Type',
       'Discount Percentage(%)', 'Rating', 'Users'],
      dtype='object')

In [36]:
df.shape   #(rews,columns)

(2784, 7)

## Data Selection and Filtering

In [37]:
df

,Product Name,Discount Prices(?),Actual Prices(?),Weight/Type,Discount Percentage(%),Rating,Users
0,Wellcore Micronised Creatine Monohydrate | Lab...,599,749,"122 g, Tropical Tango",20% off,4.3,"2,51,934"
1,BIGMUSCLES NUTRITION Premium Gold Whey Protein,"1,499","2,899","1 kg, Belgian Chocolate",48% off,4.1,"99,351"
2,NutraEats Protein Plus Supplement Whey Protein...,459,599,"200 g, Chocolate",23% off,4.3,"2,51,934"
3,NutraEats Protein Plus Supplement Whey Protein...,489,899,"300 g, Chocolate",45% off,4.3,"2,51,934"
4,NutraEats Protein Plus Supplement Whey Protein...,528,799,"250 g, Chocolate",33% off,4.2,"1,467"
...,...,...,...,...,...,...,...
2779,Vaseline Healthy Bright Sun+Pollution Protecti...,593,499,400 ml,85% off,4.4,"20,469"
2780,efatop NEXT Lotion 150ml For Intense Moisturizer,569,300,150 ml,55% off,3.9,17
2781,Rubz Cherry Blossom Body Milk with Cherry Blos...,353,525,1 L,22% off,4.1,"1,167"
2782,Parachute Advansed Advansed Soft Touch Body Lo...,349,80,800 ml,24% off,4.6,269
2783,POND's Niacinamide Nourishing Body Lotion 400 ml,241,585,400 ml,8% off,4.6,860

In [38]:
#accesing only ono columns
df['Product Name']

0       Wellcore Micronised Creatine Monohydrate | Lab...
1          BIGMUSCLES NUTRITION Premium Gold Whey Protein
2       NutraEats Protein Plus Supplement Whey Protein...
3       NutraEats Protein Plus Supplement Whey Protein...
4       NutraEats Protein Plus Supplement Whey Protein...
                              ...
2779    Vaseline Healthy Bright Sun+Pollution Protecti...
2780     efatop NEXT Lotion 150ml For Intense Moisturizer
2781    Rubz Cherry Blossom Body Milk with Cherry Blos...
2782    Parachute Advansed Advansed Soft Touch Body Lo...
2783     POND's Niacinamide Nourishing Body Lotion 400 ml
Name: Product Name, Length: 2784, dtype: object

In [39]:
#access one cloumn with periticular index
df['Product Name'][3]

'NutraEats Protein Plus Supplement Whey Protein Powder C...'

In [40]:
type(df['Product Name'])
#giving the type of data

pandas.core.series.Series

In [43]:
#acessing 2 columns
df[['Product Name','Discount Prices(?)']]

                                           Product Name Discount Prices(?)
0     Wellcore Micronised Creatine Monohydrate | Lab...                599
1        BIGMUSCLES NUTRITION Premium Gold Whey Protein              1,499
2     NutraEats Protein Plus Supplement Whey Protein...                459
3     NutraEats Protein Plus Supplement Whey Protein...                489
4     NutraEats Protein Plus Supplement Whey Protein...                528
...                                                 ...                ...
2779  Vaseline Healthy Bright Sun+Pollution Protecti...                593
2780   efatop NEXT Lotion 150ml For Intense Moisturizer                569
2781  Rubz Cherry Blossom Body Milk with Cherry Blos...                353
2782  Parachute Advansed Advansed Soft Touch Body Lo...                349
2783   POND's Niacinamide Nourishing Body Lotion 400 ml                241

[2784 rows x 2 columns]

In [44]:
df.loc[1]   #give all about data of index location 1

Product Name              BIGMUSCLES NUTRITION Premium Gold Whey Protein
Discount Prices(?)                                                 1,499
Actual Prices(?)                                                   2,899
Weight/Type                                      1 kg, Belgian Chocolate
Discount Percentage(%)                                           48% off
Rating                                                               4.1
Users                                                             99,351
Name: 1, dtype: object

In [45]:
df.iloc[1]

Product Name              BIGMUSCLES NUTRITION Premium Gold Whey Protein
Discount Prices(?)                                                 1,499
Actual Prices(?)                                                   2,899
Weight/Type                                      1 kg, Belgian Chocolate
Discount Percentage(%)                                           48% off
Rating                                                               4.1
Users                                                             99,351
Name: 1, dtype: object

In [46]:
df.loc[4,'Discount Percentage(%)']   #here we said like give the data  index 7 on discount columns

'33% off'

In [49]:
#by using iloc we access data by using only index number
df.iloc[4,4]   #4 index ,#4 stand for column with index wise

'33% off'

In [50]:
df.loc[0:3,['Discount Percentage(%)','Product Name']]   #said like give data of index from 0 to 3 of column Discount Percentage(%)','Product Name

  Discount Percentage(%)                                       Product Name
0                20% off  Wellcore Micronised Creatine Monohydrate | Lab...
1                48% off     BIGMUSCLES NUTRITION Premium Gold Whey Protein
2                23% off  NutraEats Protein Plus Supplement Whey Protein...
3                45% off  NutraEats Protein Plus Supplement Whey Protein...

In [52]:
df.iloc[0:,0:3]   #by acess by using index value by giveind row index columns index

,Product Name,Discount Prices(?),Actual Prices(?)
0,Wellcore Micronised Creatine Monohydrate | Lab...,599,749
1,BIGMUSCLES NUTRITION Premium Gold Whey Protein,"1,499","2,899"
2,NutraEats Protein Plus Supplement Whey Protein...,459,599
3,NutraEats Protein Plus Supplement Whey Protein...,489,899
4,NutraEats Protein Plus Supplement Whey Protein...,528,799
...,...,...,...
2779,Vaseline Healthy Bright Sun+Pollution Protecti...,593,499
2780,efatop NEXT Lotion 150ml For Intense Moisturizer,569,300
2781,Rubz Cherry Blossom Body Milk with Cherry Blos...,353,525
2782,Parachute Advansed Advansed Soft Touch Body Lo...,349,80
2783,POND's Niacinamide Nourishing Body Lotion 400 ml,241,585

In [54]:
#we want the like give data which rating is grater than 4.5
df[df['Rating']>4.5]

,Product Name,Discount Prices(?),Actual Prices(?),Weight/Type,Discount Percentage(%),Rating,Users
86,Wellcore Micronised Creatine Monohydrate | Lab...,599,749,"122 g, Fruit Fusion",20% off,5.0,3
97,Wellcore Micronised Creatine Monohydrate | Lab...,"1,199","1,499","250 g, Unflavored",25% off,4.8,12
106,BIGMUSCLES NUTRITION Nitra Isolate | 32g Prote...,"1,649","2,699","1 kg, Chocolate Brownie",52% off,4.9,7
117,N2B 100% Whey Gold Protein Supplement Powder W...,762,"3,750","1 kg, Gourmet Chocolate",24% off,4.7,3
175,GNC Pro Performance Power Protein Whey Protein,"3,999","2,200","4 pounds, Double Rich Chocolate",73% off,4.6,9
...,...,...,...,...,...,...,...
2744,Aveeno Active Naturals Skin Relief Moisturizin...,587,585,354 ml,78% off,4.6,64
2757,NIVEA Shea Smooth ) Deep Moisture Serum,315,279,225 ml,46% off,5.0,2
2776,DEWSOFT MOISTURIZATION LOTION,277,399,200 ml,39% off,5.0,3
2782,Parachute Advansed Advansed Soft Touch Body Lo...,349,80,800 ml,24% off,4.6,269
2783,POND's Niacinamide Nourishing Body Lotion 400 ml,241,585,400 ml,8% off,4.6,860

In [56]:
#we want the like give data which rating is grater than 4.5 give that product name only
df[df['Rating']>4.5]['Product Name']

86      Wellcore Micronised Creatine Monohydrate | Lab...
97      Wellcore Micronised Creatine Monohydrate | Lab...
106     BIGMUSCLES NUTRITION Nitra Isolate | 32g Prote...
117     N2B 100% Whey Gold Protein Supplement Powder W...
175        GNC Pro Performance Power Protein Whey Protein
                              ...
2744    Aveeno Active Naturals Skin Relief Moisturizin...
2757              NIVEA Shea Smooth ) Deep Moisture Serum
2776                        DEWSOFT MOISTURIZATION LOTION
2782    Parachute Advansed Advansed Soft Touch Body Lo...
2783     POND's Niacinamide Nourishing Body Lotion 400 ml
Name: Product Name, Length: 220, dtype: object

In [62]:
#lets use and functions
#here we said like give highest rating product which has 85% Discount Percentage(%)
df[(df['Rating']>4.5)&(df['Discount Percentage(%)']>'85% off')]    #here we probkem becz of in our funtion we str charecter ,undertsand when you use you also take int data.

,Product Name,Discount Prices(?),Actual Prices(?),Weight/Type,Discount Percentage(%),Rating,Users
1145,GLAMVEDA 2% Kojic Acid 3 Step Skincare Set â€“ F...,513,"1,148",3 Items in the set,89% off,4.9,11
1484,voorkoms Acne Scars Cure & Herbal Bath Combo F...,574,"1,494",100 g,87% off,4.7,24
1588,purobio Buy Daily Face Wash & Get Free Lavende...,910,199,100 g,87% off,4.6,7
2224,NIVEA Cocoa Nourish Lotion 400 Ml ( Pack Of 1),414,275,400 ml,9% off,4.6,15
2733,Vaseline Healthy Bright Daily Brightening Body...,270,649,400 ml,9% off,4.7,31

In [72]:
df.query("Users > '100000'").head(1)   #here we said like give data which has greater than 100000 user Users columns ,give fist one columns

,Product Name,Discount Prices(?),Actual Prices(?),Weight/Type,Discount Percentage(%),Rating,Users
0,Wellcore Micronised Creatine Monohydrate | Lab...,599,749,"122 g, Tropical Tango",20% off,4.3,"2,51,934"

## Data Cleaning & Preprocessing

In [2]:
import pandas as pd
df = pd.read_csv('total_health_supplement.csv')

In [3]:
#lets check which are column are interger or string
df.dtypes
#shit all value which containis number data that store in number format

Product Name               object
Discount Prices(?)         object
Actual Prices(?)           object
Weight/Type                object
Discount Percentage(%)     object
Rating                    float64
Users                      object
dtype: object

In [4]:
# Detect Which Values Are Not Proper Numbers
import pandas as pd

# Assuming df is already loaded
cols_to_check = ['Discount Prices(?)', 'Actual Prices(?)', 'Discount Percentage(%)', 'Users']

for col in cols_to_check:
    print(f"\nChecking column: {col}")
    invalid_rows = df[col].apply(lambda x: pd.to_numeric(str(x).replace(",", "").replace("% off", "").strip(), errors='coerce')).isna()
    if invalid_rows.any():
        print(f"Non-numeric values found in column '{col}':")
        print(df.loc[invalid_rows, col])
    else:
        print("All values are numeric (after cleaning).")

Checking column: Discount Prices(?)
All values are numeric (after cleaning).

Checking column: Actual Prices(?)
All values are numeric (after cleaning).

Checking column: Discount Percentage(%)
All values are numeric (after cleaning).

Checking column: Users
All values are numeric (after cleaning).

In [5]:
#Convert to Numeric After Cleaning
df['Discount Prices(?)'] = pd.to_numeric(df['Discount Prices(?)'].str.replace(",", "").str.strip(), errors='coerce')
df['Actual Prices(?)'] = pd.to_numeric(df['Actual Prices(?)'].str.replace(",", "").str.strip(), errors='coerce')

# Remove '% off' and convert to numeric
df['Discount Percentage(%)'] = df['Discount Percentage(%)'].str.replace('% off', '').str.strip()
df['Discount Percentage(%)'] = pd.to_numeric(df['Discount Percentage(%)'], errors='coerce')

# Remove commas in Users and convert to integer
df['Users'] = df['Users'].str.replace(",", "").str.strip()
df['Users'] = pd.to_numeric(df['Users'], errors='coerce').astype("Int64")  # Keeps NaN support

In [6]:
df

,Product Name,Discount Prices(?),Actual Prices(?),Weight/Type,Discount Percentage(%),Rating,Users
0,Wellcore Micronised Creatine Monohydrate | Lab...,599,749,"122 g, Tropical Tango",20,4.3,251934
1,BIGMUSCLES NUTRITION Premium Gold Whey Protein,1499,2899,"1 kg, Belgian Chocolate",48,4.1,99351
2,NutraEats Protein Plus Supplement Whey Protein...,459,599,"200 g, Chocolate",23,4.3,251934
3,NutraEats Protein Plus Supplement Whey Protein...,489,899,"300 g, Chocolate",45,4.3,251934
4,NutraEats Protein Plus Supplement Whey Protein...,528,799,"250 g, Chocolate",33,4.2,1467
...,...,...,...,...,...,...,...
2779,Vaseline Healthy Bright Sun+Pollution Protecti...,593,499,400 ml,85,4.4,20469
2780,efatop NEXT Lotion 150ml For Intense Moisturizer,569,300,150 ml,55,3.9,17
2781,Rubz Cherry Blossom Body Milk with Cherry Blos...,353,525,1 L,22,4.1,1167
2782,Parachute Advansed Advansed Soft Touch Body Lo...,349,80,800 ml,24,4.6,269
2783,POND's Niacinamide Nourishing Body Lotion 400 ml,241,585,400 ml,8,4.6,860

In [7]:
#lests check again
print(df.dtypes)

Product Name               object
Discount Prices(?)          int64
Actual Prices(?)            int64
Weight/Type                object
Discount Percentage(%)      int64
Rating                    float64
Users                       Int64
dtype: object

In [9]:
#lets check is there is null 
df.isnull()

,Product Name,Discount Prices(?),Actual Prices(?),Weight/Type,Discount Percentage(%),Rating,Users
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
2779,False,False,False,False,False,False,False
2780,False,False,False,False,False,False,False
2781,False,False,False,False,False,False,False
2782,False,False,False,False,False,False,False
2783,False,False,False,False,False,False,False

In [11]:
#method-2 it is best way to see is in this data set there is null or what
df.isnull().sum()
#it gives 0 that means  there is no null value

Product Name              0
Discount Prices(?)        0
Actual Prices(?)          0
Weight/Type               0
Discount Percentage(%)    0
Rating                    0
Users                     0
dtype: int64

In [12]:
#lets check is there is any duplicated
df.duplicated()
#it gives false there is no duplicate

0       False
1       False
2       False
3       False
4       False
        ...
2779    False
2780    False
2781    False
2782    False
2783    False
Length: 2784, dtype: bool

## Data Transformation

In [14]:
df

,Product Name,Discount Prices(?),Actual Prices(?),Weight/Type,Discount Percentage(%),Rating,Users
0,Wellcore Micronised Creatine Monohydrate | Lab...,599,749,"122 g, Tropical Tango",20,4.3,251934
1,BIGMUSCLES NUTRITION Premium Gold Whey Protein,1499,2899,"1 kg, Belgian Chocolate",48,4.1,99351
2,NutraEats Protein Plus Supplement Whey Protein...,459,599,"200 g, Chocolate",23,4.3,251934
3,NutraEats Protein Plus Supplement Whey Protein...,489,899,"300 g, Chocolate",45,4.3,251934
4,NutraEats Protein Plus Supplement Whey Protein...,528,799,"250 g, Chocolate",33,4.2,1467
...,...,...,...,...,...,...,...
2779,Vaseline Healthy Bright Sun+Pollution Protecti...,593,499,400 ml,85,4.4,20469
2780,efatop NEXT Lotion 150ml For Intense Moisturizer,569,300,150 ml,55,3.9,17
2781,Rubz Cherry Blossom Body Milk with Cherry Blos...,353,525,1 L,22,4.1,1167
2782,Parachute Advansed Advansed Soft Touch Body Lo...,349,80,800 ml,24,4.6,269
2783,POND's Niacinamide Nourishing Body Lotion 400 ml,241,585,400 ml,8,4.6,860

In [17]:
#sorting the value of Discount price and Actual price
df.sort_values(['Discount Prices(?)','Actual Prices(?)'])

,Product Name,Discount Prices(?),Actual Prices(?),Weight/Type,Discount Percentage(%),Rating,Users
2164,Santoor Body Lotion Whitening & UV Protection,10,375,20 ml,55,4.4,1664
144,"Yogabar 10g Protein Bar Blueberry Blast, Glute...",46,1249,"50 g, Blueberry Blast",38,4.3,6389
540,aswini Hiran Joint Energy Powder - Energise yo...,47,799,250 g,65,4.8,1368
2364,JOVEES Herbal Honey and Grapes Hand and Body L...,52,435,500 ml,35,4.6,134
1146,ANI'S Premium Quality Rose Water (Gulab Jal) W...,61,600,2 Items in the set,30,4.2,529
...,...,...,...,...,...,...,...
185,Optimum Nutrition (ON) Gold Standard 100% Prot...,7599,779,"2.27 kg, Cookies & Cream",29,3.9,479
191,MUSCLEBLAZE Biozyme Performance Whey Protein P...,10799,1999,"4 kg, Rich Chocolate",14,4.0,20927
172,Optimum Nutrition (ON) Gold Standard 100% Prot...,13254,1799,"4 kg, Vanilla Ice Cream",15,3.8,1261
238,Optimum Nutrition (ON) Gold Standard 100% Prot...,13254,1900,"4 kg, Vanilla Ice Cream",50,4.2,14690
621,G GLOWSIK Karela Jamun Powder | 11 Potent Herb...,14811,798,200 g,23,4.2,47

In [27]:
df.describe()

,Discount Prices(?),Actual Prices(?),Discount Percentage(%),Rating,Users
count,2784.000000,2784.000000,2784.000000,2784.000000,2784.0
mean,538.448276,866.650144,32.414871,4.236458,27513.137572
std,730.749290,1120.027817,21.973278,0.262913,67414.688288
min,10.000000,50.000000,1.000000,1.000000,1.0
25%,239.000000,380.000000,15.000000,4.100000,103.0
50%,359.000000,542.500000,27.000000,4.300000,964.5
75%,599.000000,950.000000,48.000000,4.400000,14167.75
max,14811.000000,29979.000000,90.000000,5.000000,398320.0

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2784 entries, 0 to 2783
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Product Name            2784 non-null   object
 1   Discount Prices(?)      2784 non-null   int64
 2   Actual Prices(?)        2784 non-null   int64
 3   Weight/Type             2784 non-null   object
 4   Discount Percentage(%)  2784 non-null   int64
 5   Rating                  2784 non-null   float64
 6   Users                   2784 non-null   Int64
dtypes: Int64(1), float64(1), int64(3), object(2)
memory usage: 155.1+ KB

In [26]:
#we finssh all operation in our data set.now our data set is 100% capable for our Machine Learning
#lets store our clean data set 
df.to_csv('final_health_supplement.csv',index=False)

we do not want to perform all operation peroform in this data set .bcz of we use Machine Learning Forwards

in on next section i starting Visualizing Data for our best Understanding

# Visualzing the Data